apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blogapp-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mazenhassan20/DevSecOps-End-to-End-Project.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: blogapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true