name: DevSecOps Secure CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'terraform/**'
      - 'k8s/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'terraform/**'
      - 'k8s/**'

jobs:
  security_scan:
    name: Infrastructure & Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: pip install checkov==3.2.19

      - name: Run Checkov
        run: |
          checkov -d . --soft-fail --no-guide --quiet
  build_and_push:
    name: Build, Scan and Push Images
    needs: security_scan 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
     
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Login to Azure Container Registry
        run: az acr login --name blogappregistry2026

      - name: Build Backend Image
        run: docker build -t blogappregistry2026.azurecr.io/backend:${{ github.sha }} ./backend

      - name: Scan Backend Image with Trivy (Security Container Scan)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'blogappregistry2026.azurecr.io/backend:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Push Backend Image to ACR
        run: docker push blogappregistry2026.azurecr.io/backend:${{ github.sha }}

      - name: Build Frontend Image
        run: docker build -t blogappregistry2026.azurecr.io/frontend:${{ github.sha }} ./frontend

      - name: Scan Frontend Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'blogappregistry2026.azurecr.io/frontend:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Push Frontend Image to ACR
        run: docker push blogappregistry2026.azurecr.io/frontend:${{ github.sha }}
